name: Automate Shoonya Data Download

on:
  schedule:
    - cron: "30 11 * * 1-5"  # Runs at 8:30 PM IST (14:30 UTC)
  workflow_dispatch:  # Enables manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas pyotp requests tqdm zipfile36
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
          pip install NorenRestApiPy concurrent.futures threading warnings datetime
      
      - name: Create service_account.json file
        run: echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Run ohlc_to_drive.py
        env:
          SHOONYA_USER: ${{ secrets.SHOONYA_USER }}
          SHOONYA_PWD: ${{ secrets.SHOONYA_PWD }}
          SHOONYA_VC: ${{ secrets.SHOONYA_VC }}
          SHOONYA_APP_KEY: ${{ secrets.SHOONYA_APP_KEY }}
          SHOONYA_IMEI: ${{ secrets.SHOONYA_IMEI }}
          SHOONYA_QR: ${{ secrets.SHOONYA_QR }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python ohlc_to_drive.py
